export type Signal = {
  ticker: string;
  momentum_pct: number;
  entry: number;
  volume: number;
  volume_avg: number;
  volume_ratio: number;
  stop: number;
  take_profit: number;
  shares: number;
  position_value: number;
  dollar_risk: number;
  source: 'scan' | 'watchlist' | string;
  as_of?: string;
  forward_probability?: number | null;
  forward_confidence?: number | null;
  forward_horizon?: number | null;
  forward_pass?: boolean | null;
  forward_model?: string | null;
  ensemble_votes?: Record<string, number> | null;
  filter_metrics?: Record<string, number> | null;
  regime?: string | null;
  regime_size_mult?: number | null;
  news_score_24h?: number | null;
  news_score_7d?: number | null;
  news_spike?: boolean | null;
  news_warning?: boolean | null;
  news_headlines?: { label?: string; title?: string }[];
  blended_score?: number | null;
  time_display?: string | null;
  after_hours?: boolean | null;
  confidence?: number | null;
  session_label?: string | null;
  context?: any;
  strategy_id?: string | null;
  strategy_rationale?: string | null;
  suggested_size_mult?: number | null;
  side?: string | null;
};

export type PortfolioSnapshot = {
  mode: string;
  cash: number;
  equity: number;
  unrealized_pnl: number;
  realized_pnl: number;
  gross_realized_pnl?: number;
  total_pnl: number;
  return_pct: number;
  total_fees_paid?: number;
  fee_impact?: any;
  open_positions: any[];
  live_note?: string;
};
